server:
  port: 8091
spring:
  application:
    name: resourceserver01
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000    
  datasource:
    url: jdbc:mariadb://192.168.1.30:3306/springboottutorial
    username: willy
    password: mO6/DHN[ry
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    org:
      springframework:
        security: INFO              
